source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HNClient-iOS', :exclusive => true do
  pod "HNClient-iOS", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HNClient-iOS", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
